<?php

namespace Crew\Unsplash;

use GuzzleHttp\Client;
use GuzzleHttp\HandlerStack;
use GuzzleHttp\Handler\CurlHandler;
use GuzzleHttp\Middleware;
use GuzzleHttp\Psr7\Uri;

use GuzzleHttp\Psr7\Request;

class HttpClient
{
	private $httpClient;
	private $host = 'api.unsplash.com';
	private $scheme = 'https';

	const TEST_MODE = 'test';
	const STAGING_MODE = 'staging';

	/**
	 * Crew\Unsplash\Connection object link to the HttpClient
	 * Need to be set on the class before running anything else
	 *
	 * @example Crew\Unsplash\HttpClient::$connection = new Crew\Unsplash\Connection();
	 * @var Crew\Unsplash\Connection
	 */
	public static $connection;

	/**
	 * Generate a new http client. Retrieve the authorization token generated by the $connection object
	 */
	public function __construct()
	{
		$this->setHostAndScheme();
		$this->httpClient = new Client(['handler' => $this->setHandler(self::$connection->getAuthorizationToken())]);
	}

	/**
	 * Send an http request through the http client.
	 * Generate a new request method in whith the http method and the URI is passed
	 * 
	 * @param  string $method http method sent
	 * @param  array $argument Array containing the URI to send the request and the parameters of the request
	 * @return GuzzleHttp\Psr7\Response
	 */
	public function send($method, $arguments)
	{
		$uri = $arguments[0];
		$params = isset($arguments[1]) ? $arguments[1] : [];

		$response = $this->httpClient->send(
			new Request($method, new Uri($uri)),
			$params
		);

		return $response;
	}

	/**
	 * Retrieve the host to which the client will send the request
	 * @return string
	 */
	public function getHost()
	{
		return $this->host;
	}

	/**
	 * Retrieve the scheme to which the client will send the request
	 * @return string
	 */
	public function getScheme()
	{
		return $this->scheme;
	}

	/**
	 * Generate a new handler that will manage the http requests.
	 *
	 * Some middleware are also configured to manage the authorization header and request URI
	 * 
	 * @param string $authorization Authorization code to pass in the header
	 * @return GuzzleHttp\HandlerStack
	 */
	private function setHandler($authorization)
	{
		$stack = new HandlerStack();

		$stack->setHandler(new CurlHandler());

		// Set authorization headers
		$this->authorization = $authorization;
		$stack->push(Middleware::mapRequest(function (Request $request) {
		    return $request->withHeader('Authorization', $this->authorization);
		}), 'set_authorization_header');
		
		// Set the request ui
		$stack->push(Middleware::mapRequest(function (Request $request) {
			$uri = $request->getUri()->withHost($this->host)->withScheme($this->scheme);

		    return $request->withUri($uri);
		}), 'set_host');

		return $stack;
	}

	/**
	 * Set the host and the scheme information depending on test or staging mode.
	 */
	private function setHostAndScheme()
	{
		if (getenv('ENV_MODE') !== null && in_array(getenv('ENV_MODE'), [self::STAGING_MODE, self::TEST_MODE])) {
			$this->host = getenv('API_HOST');
			$this->scheme = getenv('API_SCHEME');
		}
	}
}